# Generated by Django 5.2.7 on 2025-10-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prio',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
